# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-12-16 07:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateField(verbose_name='Horario')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('created_at_datetime', models.DateField(verbose_name='Fecha de creación')),
                ('updated_at_datetime', models.DateField(verbose_name='Fecha de actualización')),
                ('status', models.CharField(max_length=35, verbose_name='estado')),
            ],
            options={
                'verbose_name_plural': 'Actividades',
                'verbose_name': 'Actividad',
                'ordering': ['-created_at_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('address', models.TextField(verbose_name='dirección')),
                ('description', models.TextField(verbose_name='descripción')),
                ('created_at_datetime', models.DateField(verbose_name='Fecha de creación')),
                ('updated_at_datetime', models.DateField(verbose_name='Fecha de actualización')),
                ('disabled_at_datetime', models.DateField(blank=True, null=True, verbose_name='Fecha de deshabilitación')),
                ('status', models.CharField(max_length=35, verbose_name='estado')),
            ],
            options={
                'verbose_name_plural': 'Propiedades',
                'verbose_name': 'Propiedad',
                'ordering': ['-created_at_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at_datetime', models.DateField(verbose_name='Fecha de creación')),
                ('activity_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apiRest.Activity', verbose_name='actividad')),
            ],
            options={
                'verbose_name_plural': 'Encuestas',
                'verbose_name': 'Encuesta',
                'ordering': ['-created_at_datetime'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiRest.Property', verbose_name='propiedad'),
        ),
    ]
