# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-12-16 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiRest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at_datetime',
            field=models.DateTimeField(verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=35, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_at_datetime',
            field=models.DateTimeField(verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at_datetime',
            field=models.DateTimeField(auto_created=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='property',
            name='disabled_at_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de deshabilitación'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=35, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_at_datetime',
            field=models.DateTimeField(verbose_name='Fecha de creación'),
        ),
    ]
