# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-12-16 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiRest', '0002_auto_20211216_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='schedule',
            field=models.DateTimeField(verbose_name='Horario'),
        ),
    ]
