# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-12-17 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiRest', '0003_auto_20211216_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at_datetime',
            field=models.DateTimeField(auto_created=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_at_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
    ]
