# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-12-17 07:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiRest', '0004_auto_20211216_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at_datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=35, verbose_name='estado'),
        ),
    ]
