# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-12-17 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiRest', '0005_auto_20211217_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('cancelada', 'Cancelada')], default='activo', max_length=35, verbose_name='estado'),
        ),
    ]
